// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6BJn6YoP_9sRdXTCThgY9h9xOm3yWmO8',
    appId: '1:769652525469:web:127f5ab9f95003b8b24774',
    messagingSenderId: '769652525469',
    projectId: 'what-sup-b84ee',
    authDomain: 'what-sup-b84ee.firebaseapp.com',
    storageBucket: 'what-sup-b84ee.firebasestorage.app',
    measurementId: 'G-ZG2JGYV6ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCad3Q47aqfvHkb5mguROlGgz5aXY1opWQ',
    appId: '1:769652525469:android:4f9254c1dc011a74b24774',
    messagingSenderId: '769652525469',
    projectId: 'what-sup-b84ee',
    storageBucket: 'what-sup-b84ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDOCWDSGbLWOyc-BfySTGR-Xgp_yr3DLM',
    appId: '1:769652525469:ios:384337d37588d153b24774',
    messagingSenderId: '769652525469',
    projectId: 'what-sup-b84ee',
    storageBucket: 'what-sup-b84ee.firebasestorage.app',
    iosBundleId: 'com.example.whatsUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDOCWDSGbLWOyc-BfySTGR-Xgp_yr3DLM',
    appId: '1:769652525469:ios:384337d37588d153b24774',
    messagingSenderId: '769652525469',
    projectId: 'what-sup-b84ee',
    storageBucket: 'what-sup-b84ee.firebasestorage.app',
    iosBundleId: 'com.example.whatsUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6BJn6YoP_9sRdXTCThgY9h9xOm3yWmO8',
    appId: '1:769652525469:web:1f5f44e5fdbf1808b24774',
    messagingSenderId: '769652525469',
    projectId: 'what-sup-b84ee',
    authDomain: 'what-sup-b84ee.firebaseapp.com',
    storageBucket: 'what-sup-b84ee.firebasestorage.app',
    measurementId: 'G-M18806EN3R',
  );
}
